TMSProject/WebProject/Controllers/TransactionsController.cs
using BLL.interfaces;
using DAL.Model;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using WebProject.Models.dto;

namespace WebProject.Controllers
{
    public class TransactionsController : Controller
    {
        private readonly ITransactionService _transactionService;
        public TransactionsController(ITransactionService transactionService)
        {
            _transactionService = transactionService;
        }

        [HttpGet]
        public IActionResult AddTransaction(TransactionDto trDto)
        {
            return View(trDto);
        }

        [HttpPost]
        public IActionResult Add(TransactionDto tr)
        {
            _transactionService.Add(tr);

            return RedirectToRoutePermanent(new { controller = "User", action = "GetAllClients" });
        }

        [HttpGet]
        public IActionResult GetAccountIncomingTransactionsHistory(int id)
        {
            var model = _transactionService.GetAllIncomingTransactions(id);

            return View(model);
        }

        [HttpGet]
        public IActionResult GetAccountOutcomingTransactionsHistory(int id)
        {
            var model = _transactionService.GetAllOutcomingTransactions(id);

            return View(model);
        }


        public decimal GetAmount(int id)
        {
            var incTr = _transactionService.GetAllIncomingTransactions(id);
            var outcTr = _transactionService.GetAllOutcomingTransactions(id);

            return incTr.Sum(t => t.Amount) - outcTr.Sum(t => t.Amount);
        }
    }
}

TMSProject/WebProject/Views/Transactions/AddTransaction.cshtml
@using DAL.Model 
@using WebProject.Models.dto 
@model TransactionDto

<body>
    @using (Html.BeginForm("Add", "Transactions", FormMethod.Post))
    {
        @Html.ValidationSummary()
        //Antiforgerytoken
        <table class="table">
            <tr>
                @Html.HiddenFor(model => model.SenderId)

                <td class="btn-dark">@Html.LabelFor(model => model.Amount)</td>
                <td class="btn-outline-secondary">@Html.EditorFor(model => model.Amount)</td>
                <tr/>
            <tr>
                <td class="btn-dark">Account</td>
                <td class="btn-outline-secondary">@Html.EditorFor(model => model.ReciverId)</td>

            </tr>
        </table>

        <br />

        <p><input type="submit" class="btn btn-dark" value="submit" /></p>
    }
</body>

TMSProject/WebProject/Views/Transactions/GetAccountIncomingTransactionsHistory.cshtml
@using DAL.Model
@model List<IncomingTransaction>


<div class="align-content-center">

    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">from</th>
                <th scope="col">amount</th>
                <th scope="col">date</th>
                <th scope="col">Sent from account id</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var tr in Model)
            {
                <tr>
                    <td scope="row">@tr.Source</td>
                    <td> <div id="am">@tr.Amount $</div></td>

                    <td>
                        @tr.Date.Month
                        /
                        @tr.Date.Day
                        /
                        @tr.Date.Year
                    </td>

                    <td>@tr.SenderBankAccountId</td>
                </tr>
            }
        </tbody>

    </table>

</div>

TMSProject/WebProject/Views/Transactions/GetAccountOutcomingTransactionsHistory.cshtml
@using DAL.Model
@model List<OutcomingTransaction>


<div class="align-content-center">

    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th scope="col">from</th>
                <th scope="col">amount</th>
                <th scope="col">date</th>
                <th scope="col">Sent from account id</th>
            </tr>
        </thead>

        <tbody>
            @foreach (var tr in Model)
            {
                <tr>
                    <td scope="row">@tr.Source</td>
                    <td>@tr.Amount $</td>

                    <td>
                        @tr.Date.Month
                        /
                        @tr.Date.Day
                        /
                        @tr.Date.Year
                    </td>

                    <td>@tr.SenderBankAccountId</td>
                </tr>
            }
        </tbody>

    </table>

</div>