TMSProject/WebProject/Controllers/PersonalAccountsController.cs
using BLL.interfaces;
using DAL.Model;
using WebProject.Models.dto;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;

namespace WebProject.Controllers
{
    public class PersonalAccountsController : Controller
    {
        private readonly IAccountService _accountService;
        private readonly ITransactionService _transactionService;
        public PersonalAccountsController(IAccountService accountService, ITransactionService transactionService)
        {
            _accountService = accountService;
            _transactionService = transactionService;
        }
        //take id from claim

        //
        public IActionResult GetAllUserAccs(int id)
        {
            var model = new List<UserPersonalAccount>();

            model = _accountService.GetAll().Where(x => x.UserId == id).ToList();

            foreach (var acc in model)
            {
                acc.Amount = _transactionService.GetAmount(acc.Id);
            }

            return View(model);
        }


        [HttpGet]
        public IActionResult AddNewAccountPage(PersonalAccountDto acc)
        {
            return View(acc);
        }


        [HttpPost]
        public IActionResult AddNewAccount(PersonalAccountDto acc)
        {
            var newAcc = new UserPersonalAccount();

            newAcc.UserId = acc.UserId;

            _accountService.Add(newAcc);

            return Redirect($"GetAllUserAccs/{acc.UserId}");
        }


    }
}

TMSProject/WebProject/Views/PersonalAccounts/AddNewAccountPage.cshtml
@using WebProject.Models.dto
@model PersonalAccountDto
<head>

</head>
<body>
    @using (Html.BeginForm("AddNewAccount", "PersonalAccounts", FormMethod.Post))
    {
        <table>
            <tr>                
                    @Html.HiddenFor(model => model.UserId)
            </tr>            
        </table>

        <p><input type="submit" class="btn btn-primary" value="submit" /></p>
    }
</body>

TMSProject/WebProject/Views/PersonalAccounts/GetAllUserAccs.cshtml
@using DAL.Model
@model List<DAL.Model.UserPersonalAccount>

<div class="text-center">

    <table class="table">
        <tbody class="btn-dark">
            <tr>
                <th>account ID</th>
                <th>state</th>
                <th>operation</th>
                <th>incoming transactions</th>
                <th>outcoming transactions</th>
            </tr>
        </tbody>

        @foreach (var acc in Model)
        {
            <tr>
                <td>@acc.Id</td>
                <td>@acc.Amount $</td>

                <td>
                    @Html.ActionLink(
                       "Transfer",
                       "AddTransaction",
                       "Transactions",
                          new WebProject.Models.dto.TransactionDto() { SenderId = acc.Id },
                          new { type = "button", @class = " btn btn-secondary" })
                </td>

                <td>
                    @Html.ActionLink("Open history", "GetAccountIncomingTransactionsHistory", "Transactions",
                         new { id = acc.Id },
                         new { type = "button", @class = "btn btn-secondary" })
                </td>
                <td>
                    @Html.ActionLink("Open history", "GetAccountOutcomingTransactionsHistory", "Transactions",
                         new { id = acc.Id },
                         new { type = "button", @class = "btn btn-secondary" })
                </td>

            </tr>
        }
    </table>

    @Html.ActionLink("open new account", "AddNewAccountPage", "PersonalAccounts", new WebProject.Models.dto.PersonalAccountDto() { UserId = Model.First().UserId }, new { type = "button", @class = "btn btn-dark" })

</div>